declare -a graphs=("airlines"
                   "bergen"
                   "ca-CondMat"
                   "ca-HepPh"
                   "celegans"
                   "cit-HepPh"
                   "cit-HepTh"
                   "codeminer"
                   "cond-mat"
                   "cpan-authors"
                   "cpan-distributions"
                   "diseasome"
                   "dolphins"
                   "email-Enron"
                   "football"
                   "hep-th"
                   "hex"
                   "karate"
                   "lesmiserables"
                   "loc-brightkite_edges"
                   "netscience"
                   "photoviz_dynamic"
                   "polblogs"
                   "polbooks"
                   "power"
                   "soc-Epinions1"
                   "soc-Slashdot0811"
                   "sp_data_school_day_2"
                   "twittercrawl"
                   "word_adjacencies"
                   "yeast")

for graph in "${graphs[@]}"; do
    wc $graph.txt
done